apiVersion: skaffold/v4beta11
kind: Config
manifests:
  rawYaml:
    - ./infra/k8s/*
build:
  # local:
  #   push: false
  googleCloudBuild:
    projectId: ticketing-dev-430721
  tagPolicy:
    sha256: {}
  artifacts:
    - image: us.gcr.io/ticketing-dev-430721/auth
      context: auth
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: us.gcr.io/ticketing-dev-430721/client
      context: client
      sync:
        manual:
          - src: '**/*.ts'
            dest: .
      docker:
        dockerfile: Dockerfile
  